name: Excel Diff on PR

on:
  pull_request:
    paths:
      - '**.xlsx'

permissions:
  pull-requests: write

jobs:
  excel_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch PR and base commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl tabulate

      - name: Find changed Excel files
        id: files
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '.xlsx' || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT


      - name: Compare Excel files and generate report
        if: steps.files.outputs.files != ''
        run: |
          mkdir -p diff_reports
          for file in ${{ steps.files.outputs.files }}; do
            git show ${{ github.event.pull_request.base.sha }}:$file > old.xlsx || touch old.xlsx
            cp $file new.xlsx
            python .github/scripts/compare_excels.py old.xlsx new.xlsx diff_reports/$file.diff.txt
          done

      - name: Upload diff report artifact
        if: steps.files.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: excel-diff-reports
          path: diff_reports/

#      - name: Post diff as PR comment
#        if: steps.files.outputs.files != ''
#        run: |
#          for report in diff_reports/*.diff.txt; do
#            body="**Excel file difference for:** $(basename $report .diff.txt)\n\n\`\`\`markdown\n$(cat $report)\n\`\`\`"
#            gh pr comment ${{ github.event.pull_request.number }} --body "$body"
#          done
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
